version: '3.8'

services:
  app:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: laravel-app
  working_dir: /var/www
  volumes:
    - ./backend:/var/www
  ports:
    - "9000:9000"
  depends_on:
    - mysql
  networks:
    - app-network



  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: image_managerdb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mysql-data: {}

networks:
  app-network:
    driver: bridge
